software_design_task:
  description: >
    Conduct a thorough design issue analysis about {code}
    Make sure you find any interesting and relevant.
  expected_output: >
    A list with 5 bullet points of the most relevant information about the design issues in {code}
  agent: software_designer

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst
